export const SKILLS = [
    "c",
    "c++",
    "java",
    "python",
    "javascript",
    "typescript",
    "react",
    "node.js",
    "express",
    "mongodb",
    "mysql",
    "sql",
    "docker",
    "azure",
    "aws",
    "gcp",
    "tensorflow",
    "keras",
    "pytorch",
    "scikit-learn",
    "numpy",
    "pandas",
    "nlp",
    "machine learning",
    "deep learning",
    "fastapi",
    "flask",
    "streamlit",
    "git",
    "github",
    "postman",
    "html",
    "css",
    "redis",
    "kubernetes",
];